[package]
name = "yew-app"
version = "0.1.0"
authors = ["You <you@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
web_logger = "0.2"
yew = "0.10.0"
yew-router = "0.7.0"
wasm-bindgen = "0.2.54"
wee_alloc = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.2"